coupon/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views

app_name = 'coupon'
urlpatterns = [
    path(_('apply/'), views.coupon_apply, name='coupon_apply'),
]

jeff_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.utils.translation import gettext_lazy as _
from django.conf.urls.i18n import i18n_patterns

from payment import webhook

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path(_('cart/'), include('user_cart.urls', namespace='user_cart')),
    path(_('order/'), include('order.urls', namespace='order')),
    path(_('payment/'), include('payment.urls', namespace='payment')),
    path(_('coupon/'), include('coupon.urls', namespace='coupon')),
    path('rosetta/', include('rosetta.urls')),
    path('', include('shop.urls', namespace='shop')),
)

urlpatterns += [path('payment/webhook/', webhook.stripe_webhook, name='webhook')]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _
from . import views

app_name = 'order'

urlpatterns = [
     path(_('create/'), views.create_order, name='create_order'), 
     path('admin_order_detail/<int:order_id>', views.admin_order_detail, name='admin_order_detail'),
     path('admin_order_detail/<int:order_id>/pdf', views.admin_order_pdf, name='admin_order_pdf'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:product_id>/<slug:product_slug>/', views.product_detail, name='product_detail'),
]

user_cart/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _

app_name = 'user_cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path(f'<int:product_id>/{_('add')}', views.add_product_to_cart, name='cart_add'),
    path(f'<int:product_id>/{_('remove')}', views.remove_all_product_item_from_cart, name='cart_remove'),
]

user_cart/models.py
from django.db import models

# Create your models here.

user_cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
class ProductAddToCart(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label=_("quantity"))
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

user_cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.urls import reverse

from shop.models import Product
from .cart_config import UserCart
from .forms import ProductAddToCart
from coupon.forms import CouponApplyForm


# Create your views here.

@require_POST
def add_product_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    form = ProductAddToCart(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
    cart = UserCart(request)
    cart.add(product, cd['quantity'], cd['override'])
    return redirect(reverse('user_cart:cart_detail'))

@require_POST
def remove_one_product_item_from_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart = UserCart(request)
    cart.remove_one(product)
    return redirect(reverse('user_cart:cart_detail'))

@require_POST
def remove_all_product_item_from_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart = UserCart(request)
    cart.remove_all(product)
    return redirect(reverse('user_cart:cart_detail'))

def clear_cart(request):
    cart = UserCart(request)
    cart.clear_cart()
    return redirect(reverse('user_cart:cart_detail'))

def cart_detail(request):
    form = CouponApplyForm()
    cart = UserCart(request)
    for item in cart:
        item['update_item_quantity_form'] = ProductAddToCart(initial={'quantity': item['quantity'], 'override': True})
        print('item_price:', item['price'])
        print('item_total_price:', item['total_price'])
    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form': form})

    

    

user_cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}
  {% trans "Your shopping cart" %}
{% endblock %}

{% block content %}
  <h1>{% trans "Your shopping cart" %}</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>{% trans "Image" %}</th>
        <th>{% trans "Product" %}</th>
        <th>{% trans "Quantity" %}</th>
        <th>{% trans "Remove" %}</th>
        <th>{% trans "Unit price" %}</th>
        <th>{% trans "Price" %}</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}
                {% else %}{% static 'img/no_image.jpg' %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url 'user_cart:cart_add' product.id %}" method="post">
                {{ item.update_item_quantity_form.quantity }}
                {{ item.update_item_quantity_form.override }}
                <input type="submit" value="{% trans 'Update' %}">
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url 'user_cart:cart_remove' product.id %}" method="post">
                <input type="submit" value="{% trans 'Remove' %}">
                {% csrf_token %}
              </form>
            </td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      {% if cart.coupon %}
      <h1>{% trans "new" %}</h1>
        <tr class="subtotal">
          <td>{% trans "Subtotal" %}</td>
          <td colspan="4"></td>
          <td class="num">${{ cart.get_total_price|floatformat:2 }}</td>
        </tr>
        <tr>
          <td>
            {% blocktrans with code=cart.coupon.code discount=cart.coupon.discount %}
              "{{ code }}" ({{ discount }}% off)
              {% endblocktrans %}
          </td>
          <td colspan="4"></td>
          <td class="num neg">
            - ${{ cart.get_discount|floatformat:2 }}
          </td>
        </tr>
      {% endif %}
      <tr class="total">
        <td>{% trans "Total" %}</td>
        <td colspan="4"></td>
        <td class="num">
          ${{ cart.get_price_after_discount|floatformat:2 }}
        </td>
      </tr>
    </tbody>
  </table>
  
  {% comment %} {% if recommended_products %}
    <div class="recommendations cart">
      <h3>People who bought this also bought</h3>
      {% for p in recommended_products %}
        <div class="item">
          <a href="{{ p.get_absolute_url }}">
            <img src="{% if p.image %}{{ p.image.url }}{% else %}
            {% static 'img/no_image.jpg' %}{% endif %}">
          </a>
          <p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
        </div>
      {% endfor %}
    </div>
  {% endif %} {% endcomment %}

  <p>{% trans "Apply a coupon" %}:</p>
  <form action="{% url 'coupon:coupon_apply' %}" method="post">
    {{ coupon_apply_form }}
    <input type="submit" value='{% trans "Apply" %}'>
    {% csrf_token %}
  </form>
  <p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="button
    light">{% trans "Continue shopping" %}</a>
    <a href="{% url 'order:create_order' %}" class="button">{% trans "Checkout" %}</a>
  </p>
{% endblock %}