jeff_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.utils.translation import gettext_lazy as _
from django.conf.urls.i18n import i18n_patterns

from payment import webhook

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path(_('cart/'), include('user_cart.urls', namespace='user_cart')),
    path(_('order/'), include('order.urls', namespace='order')),
    path(_('payment/'), include('payment.urls', namespace='payment')),
    path(_('coupon/'), include('coupon.urls', namespace='coupon')),
    path('rosetta/', include('rosetta.urls')),
    path('', include('shop.urls', namespace='shop')),
)

urlpatterns += [path('payment/webhook/', webhook.stripe_webhook, name='webhook')]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:product_id>/<slug:product_slug>/', views.product_detail, name='product_detail'),
]

user_cart/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _

app_name = 'user_cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path(f'<int:product_id>/{_('add')}', views.add_product_to_cart, name='cart_add'),
    path(f'<int:product_id>/{_('remove')}', views.remove_all_product_item_from_cart, name='cart_remove'),
]

shop/models.py
from django.db import models
from django.urls import reverse

from parler.models import TranslatableModel, TranslatedFields
# Create your models here.

class Category(TranslatableModel):
    translations = TranslatedFields(
        name = models.CharField(max_length=250),
        slug = models.SlugField()
    )
    class Meta:
        # ordering = ['name']
        # indexes = [models.Index(fields=['name'])]
        verbose_name = 'category'
        verbose_name_plural = 'categories'


    def __str__(self):
        return str(self.name)
    
    def get_absolute_url(self):
        return reverse("shop:product_list_by_category", args=[self.slug])
    
    
class Product(TranslatableModel):
    translations = TranslatedFields(
        name = models.CharField(max_length=250),
        slug = models.SlugField(),
        description = models.TextField(),
    )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product', blank=True)
    rating = models.IntegerField(default=0)
    availability = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')


    class Meta:
        ordering = ["-created"]

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])
    
    def __str__(self):
        return str(self.name)
    

shop/views.py
from django.shortcuts import render, get_object_or_404

from .models import Category, Product
from user_cart.forms import ProductAddToCart

# Create your views here.

def product_list(request, category_slug=None):
    category = None
    products = Product.objects.filter(availability=True)
    categories = Category.objects.all()
    if category_slug:
        language = request.LANGUAGE_CODE
        category = get_object_or_404(
            Category,
            translations__language_code=language,
            translations__slug=category_slug,
            )
        print(category)
        products = Product.objects.filter(category=category)

    return render(request, "shop/product/list.html", {
        'products': products,
        'categories': categories,
        'category': category
    })
 
def product_detail(request, product_id, product_slug):
    '''To get product details by checking the database with the product_id, product_slug, and its availability'''
    language = request.LANGUAGE_CODE
    product = get_object_or_404(
        Product,
        availability=True,
        id=product_id,
        translations__language_code=language,
        translations__slug=product_slug
        )
    form = ProductAddToCart()
    return render(request, "shop/product/detail.html", {'product':product, 'cart_product_form': form})

shop/templates/shop/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}{% trans "My shop" %}{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
  </head>
  <body>
    <div id="header">
      <a href="/" class="logo">{% trans "My shop" %}</a>
      {% comment %}  {% endcomment %}
      {% get_current_language as LANGUAGE_CODE %}
      {% get_available_languages as LANGUAGES %}
      {% get_language_info_list for LANGUAGES as languages %}
      <div class="languages">
        <p>{% trans "Language" %}:</p>
        <ul class="languages">
          {% for language in languages %}
            <li>
              <a href="/{{ language.code }}/"
              {% if language.code == LANGUAGE_CODE %} class="selected"{% endif %}>
                {{ language.name_local|capfirst }}
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
      {% comment %}  {% endcomment %}
    </div>
    <div id="subheader">
      <div class="cart">
        {% with total_items=cart|length %}
          {% if total_items > 0 %}
            {% trans "Your cart" %}:
            <a href="{% url 'user_cart:cart_detail' %}">
              {% comment %} {{ total_items }} item{{ total_items|pluralize }},
              ${{ cart.get_total_price }} {% endcomment %}
              {% blocktrans with total=cart.get_total_price count items=total_items %}
                {{ items }} item, ${{total}}
              {% plural %}
                {{ items }} items, ${{total}}
              {% endblocktrans %}
            </a>
          {% else %}
            {% trans "Your cart is empty." %}
          {% endif %}
        {% endwith %}
      </div>
    </div>
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>