jeff_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.utils.translation import gettext_lazy as _
from django.conf.urls.i18n import i18n_patterns

from payment import webhook

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path(_('cart/'), include('user_cart.urls', namespace='user_cart')),
    path(_('order/'), include('order.urls', namespace='order')),
    path(_('payment/'), include('payment.urls', namespace='payment')),
    path(_('coupon/'), include('coupon.urls', namespace='coupon')),
    path('rosetta/', include('rosetta.urls')),
    path('', include('shop.urls', namespace='shop')),
)

urlpatterns += [path('payment/webhook/', webhook.stripe_webhook, name='webhook')]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _
from . import views
from . import webhook

app_name = 'payment'

urlpatterns = [
    path(_('process/'), views.process, name='process'),
    path(_('completed/'), views.completed, name='completed'),
    path(_('cancelled'), views.cancelled, name='cancelled'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:product_id>/<slug:product_slug>/', views.product_detail, name='product_detail'),
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.urls import reverse

import stripe
from decimal import Decimal

from order.models import Order

stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION

# Create your views here.

def process(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order, id=order_id)
    if request.method == 'POST':
        success_url = request.build_absolute_uri(reverse('payment:completed'))
        cancel_url = request.build_absolute_uri(reverse('payment:cancelled'))

        session_data = {
            'line_items': [],
            'mode': 'payment',
            'success_url': success_url,
            'cancel_url': cancel_url,
            'client_reference_id': order.id,
        }
        for items in order.items.all():
            session_data['line_items'].append({
                    "price_data": {
                        "currency": "usd",
                        "unit_amount": int(items.unit_price * Decimal('100')),
                        "product_data": {"name": items.product.name}
                        },
                    "quantity": items.quantity
                    })
            if order.coupon:
                stripe_coupon = stripe.Coupon.create(name=order.coupon.code, percent_off=order.discount, duration='once')
                session_data['discounts'] = [{'coupon': stripe_coupon.id}]
        session = stripe.checkout.Session.create(**session_data)
        return redirect(session.url, code=303)
    else:
        return render(request, 'payment/process.html', locals())



def completed(request):
    return render(request, 'payment/completed.html')


def cancelled(request):
    return render(request, 'payment/cancelled.html')

payment/templates/payment/cancelled.html
{% extends "shop/base.html" %}
{% load i18n %}


{% block title %}{% trans "Payment canceled" %}{% endblock %}

{% block content %}
  <h1>{% trans "Your payment has not been processed" %}</h1>
  <p>{% trans "There was a problem processing your payment." %}</p>
{% endblock %}

payment/templates/payment/completed.html
{% extends "shop/base.html" %}
{% load i18n %}


{% block title %}{% trans "Payment successful" %}{% endblock %}

{% block content %}
  <h1>{% trans "Your payment was successful<" %}</h1>
  <p>{% trans "Your payment has been processed successfully." %}</p>
{% endblock %}

payment/templates/payment/process.html
{% extends "shop/base.html" %}
{% load static %}
{% load i18n %}


{% block title %}{% trans "Pay your order" %}{% endblock %}

{% block content %}
  <h1>{% trans "Order summary" %}</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>{% trans "Image" %}</th>
        <th>{% trans "Product" %}</th>
        <th>{% trans "Price" %}</th>
        <th>{% trans "Quantity" %}</th>
        <th>{% trans "Total" %}</th>
      </tr>
    </thead>
    <tbody>
      {% for item in order.items.all %}
        <tr class="row{% cycle '1' '2' %}">
          <td>
            <img src="{% if item.product.image %}{{ item.product.image.url }}
            {% else %}{% static 'img/no_image.png' %}{% endif %}">
          </td>
          <td>{{ item.product.name }}</td>
          <td class="num">${{ item.unit_price }}</td>
          <td class="num">{{ item.quantity }}</td>
          <td class="num">${{ item.get_cost }}</td>
        </tr>
      {% endfor %}
      {% if order.coupon %}
        <tr class="subtotal">
          <td>{% trans "Subtotal" %}</td>
          <td colspan="3"></td>
          <td class="num">
            ${{ order.get_total_cost_before_discount|floatformat:2 }}
          </td>
        </tr>
        <tr>
          <td>
            {% blocktrans with code=order.coupon.code discount=order.discount %}
              "{{code}}" ({{ discount }}% off)
            {% endblocktrans %}
          </td>
          <td colspan="3"></td>
          <td class="num neg">
            - ${{ order.get_discount|floatformat:2 }}
          </td>
        </tr>
      {% endif %}
      <tr class="total">
        <td colspan="4">{% trans "Total" %}</td>
        <td class="num">${{ order.get_total_cost }}</td>
      </tr>
    </tbody>
  </table>
  <form action="{% url 'payment:process' %}" method="post">
    <input type="submit" value="Pay now">
    {% csrf_token %}
  </form>
{% endblock %}